# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Some Check
      uses: fjogeleit/http-request-action@v1
      id: LogintoSite
      with:
         url: 'http://3.109.155.17:8000/api/account/login'
         method: 'POST'
         customHeaders: '{"Content-Type": "application/json"}'
         data: '{"email": "sohail@email.com1", "password": "Abc@12345"}'
    - name: Show Response
      run: |
        echo ${{ fromJson(steps.LogintoSite.outputs.response).status }}
    - name: Fail     
      run: if [[ ${{ fromJson(steps.LogintoSite.outputs.response).status }} != 200 ]];  then exit 1; else exit 0; fi
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
